
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";



CREATE TABLE `airline` (
  `AIRLINE_ID` varchar(10) NOT NULL,
  `AIRLINE_NAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`AIRLINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


INSERT INTO `airline` (`AIRLINE_ID`, `AIRLINE_NAME`) VALUES
('AA', 'American Airlines'),
('DL', 'Delta Airlines'),
('UA', 'United Airlines'),
('SW', 'Southwest Airlines'),
('BA', 'British Airways'),
('AF', 'Air France');


CREATE TABLE `airport` (
  `A_NAME` varchar(50) NOT NULL,
  `STATE` varchar(30) NOT NULL,
  `COUNTRY` varchar(30) NOT NULL,
  `C_NAME` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `city` (
  `C_NAME` varchar(30) NOT NULL,
  `STATE` varchar(30) NOT NULL,
  `COUNTRY` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `contains` (
  `A_NAME` varchar(50) DEFAULT NULL,
  `AIRLINE_ID` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `flight` (
  `SOURCE` varchar(30) NOT NULL,
  `DESTINATION` varchar(30) NOT NULL,
  `DEPARTURE` varchar(5) DEFAULT NULL,
  `ARRIVAL` varchar(5) DEFAULT NULL,
  `DURATION` varchar(5) DEFAULT NULL,
  `FLIGHT_CODE` char(10) NOT NULL,
  `AIRLINE_ID` varchar(10) DEFAULT NULL,
  `PRICE_BUSINESS` int(15) DEFAULT NULL,
  `PRICE_ECONOMY` int(15) DEFAULT NULL,
  `PRICE_STUDENTS` int(15) DEFAULT NULL,
  `PRICE_DIFFERENTLYABLED` int(15) DEFAULT NULL,
  `DATE` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `pass` (
  `PASSPORT_NO` char(8) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `passenger` (
  `FNAME` varchar(50) NOT NULL,
  `MNAME` varchar(50) DEFAULT NULL,
  `LNAME` varchar(50) NOT NULL,
  `PASSPORT_NO` char(8) NOT NULL,
  `AGE` int(3) DEFAULT NULL,
  `SEX` char(1) DEFAULT NULL,
  `PHONE` char(10) DEFAULT NULL,
  `ADDRESS` varchar(50) DEFAULT NULL,
  `FLIGHT_CODE` char(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `price` (
  `PRICE` int(20) DEFAULT NULL,
  `TYPE` char(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `selected` (
  `FLIGHT_CODE` char(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `ticket` (
  `TICKET_NO` int(11) NOT NULL,
  `PRICE` int(15) DEFAULT NULL,
  `SOURCE` varchar(30) DEFAULT NULL,
  `DESTINATION` varchar(30) DEFAULT NULL,
  `DATE_OF_TRAVEL` date DEFAULT NULL,
  `PASSPORT_NO` char(8) DEFAULT NULL,
  `FLIGHT_CODE` char(10) DEFAULT NULL,
  `TYPE` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `airline`
  ADD PRIMARY KEY (`AIRLINE_ID`);


ALTER TABLE `airport`
  ADD PRIMARY KEY (`A_NAME`);

ALTER TABLE `city`
  ADD PRIMARY KEY (`C_NAME`);


ALTER TABLE `flight`
  ADD PRIMARY KEY (`FLIGHT_CODE`);


ALTER TABLE `passenger`
  ADD PRIMARY KEY (`PASSPORT_NO`);


ALTER TABLE `ticket`
  ADD PRIMARY KEY (`TICKET_NO`);


ALTER TABLE `ticket`
  MODIFY `TICKET_NO` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;

